# SEO settings
title: "Copyleft.io"
description: "Open Source Hobbyists serving the communities where we live, learn, work, and play."
keywords: "hobbyist, open source, copyleft, copyleft.io, copyleft.cloud, starterlog, starterlog.io, basestation, starterlog-theme"
url: https://copyleft.io #site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
repo: https://github.com/Copyleft-io/copyleft-io.github.io
#disqus_shortname: "FellowHobbyist"
#twitter_username: "FelloWHobbyist"
#comments: true

# Build settings
#permalink   : /:year/:title/
permalink: /:title/
markdown    : kramdown
highlighter : rouge

kramdown:
    syntax_highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed # expanded

include: ['_pages']

# Author settings
author:
  name     : "Brian Hooper"
  job      : "Hobbyist and Technology Professional"
  bio      : "An open source workafrolic who enjoys service the communities where we live, learn, work, and play."
  thumb    : /images/author.jpg
  email    : afellowhobbyist@gmail.com
  url      : http://fellowhobbyist.github.io
  github   : http://github.com/fellowhobbyist
  twitter  : http://twitter.com/fellowhobbyist
  linkedin : http://linkedin.com/in/fellowhobbyist

gems: [jekyll-paginate]
